#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

if [ -e /usr/local/share/zsh-completions ]; then
    fpath=(/usr/local/share/zsh-completions $fpath)
fi

if [ -e /usr/local/share/zsh/site-functinos ]; then
    fpath=(/usr/local/share/zsh/site-functions $fpath)
fi

# Customize to your needs...
alias la="ls -a"
alias ll="ls -l"
alias rmrf="rm -rf"
alias ps="ps -ef"

alias vibash="nvim ~/.bashrc"
alias sobash="source ~/.bashrc"
alias vizsh="nvim ~/.zshrc"
alias vizshl='nvim ~/.zshrc.local'
alias sozsh="source ~/.zshrc"

alias vi="nvim"
alias v="nvim"
alias cdg="cd $GOPATH/src"

#git commands
alias gclear='git pull;git branch --merged | egrep -v "\*|master|main" | xargs git branch -D;git fetch --prune'
alias gcom='git add .;git commit -m "fix";git push'
alias gurl='git remote get-url origin'
alias subclone='git clone --recursive'

alias kindsh='docker exec kind-control-plane crictl'


#docker commands
alias d='docker'
alias dc='docker compose'
alias compose='docker compose'
alias dockersh='docker run --privileged --tty --interactive --pid=host alpine nsenter -t 1 -m'

export PATH=$PATH:$HOME/go/bin

alias -s {sh,md,txt,json,yaml,yml,toml,rs,go,cs,ts,html}=vim

[ -f ~/.zshrc.local ] && source ~/.zshrc.local

source <(kubectl completion zsh)
source <(helm completion zsh)
source <(lgs completion zsh)

test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

export PATH=/Users/bando-shintaro/.tiup/bin:$PATH
export PATH=/Users/bando-shintaro/.go-tpc/bin:$PATH
